### ISSUE TITLE
Add UTF-8 encoding for email

### ISSUE THREAD

**Issue by energy01** [linknx/linknx#1]

**Comment by 2franix** [comment]
There is still an issue with the subject line. The subject is one header and it cannot be encoded with anything but ASCII.
A workaround consist in encoding the header either in Base64 or Quoted Printable. Here is the subject line *Présence* encoded in QP:
=?utf-8?Q?Pr=C3=A9sence?=
 
I am still looking for a library that would help converting utf-8 => [Quoted Printable, Base64]

**Comment by 2franix** [comment]
With this issue been implemented, it is recommended to use utf8 to encode the XML config (this is the default encoding assumed for XML anyway). Doing so, any kind of character in emails (either in body or in subject line) will be rendered as expected on the email client's end.
