### ISSUE TITLE
Autotools input files get changed with first "make"

### ISSUE THREAD

**Issue by 2franix** [linknx/linknx#15]
Based on 8d612bf, "make" runs aclocal, automake and autoconf. These will change Makefile.inS and aclocal.m4.
As these files are input files for autotools, having them changed when running make is surprising. Investigation is needed.

**Comment by tru7** [comment]
@2franix This is normal for repositories from github because "git clone" does not keep file timestamps. Unfortunately this breaks build logic for make (if autotools are installed). There have been lots of discussions about this. We could add the macro AM_MAINTAINER_MODE in configure.ac (no problem with me) but then we always have to make sure that all files have to be regenerated for commit. Read about this on https://www.gnu.org/software/automake/manual/html_node/maintainer_002dmode.html

**Comment by 2franix** [comment]
OK, I see the problem, thanks @tru7. This is somewhat related to my
decision to have the generated files for the build system under version
control. My intent was to reduce the burden put on end users and avoid
them to have to run ./bootstrap.sh before compiling the source. But at
that time I was not aware of such consequence, therefore it may be time
to think about it again. 

Several options: 

1- we set maintainer mode and as you mentioned, we take care of having
the build system regenerated before commit. This is not that crucial for
master but it is for release branches (those that end user are meant to
download) 

2- we set maintainer mode for master only. This reduces the risk of
forgetting to regenerate the build system in branches targeting
end-users. But there is still a risk to forget to remove the maintainer
mode when creating a release branch or merging into it. 

3- we go back on the decision to have the generated files under version
control in master. We can even put them in .gitignore so that our
sandboxes remain neat and clear. This is fine for master, as it is aimed
at developers only. In release branches, we get rid of the .gitignore
entries for these files and we put them under version control. Doing so,
the branch is ready to build out of the box. Unless we merge a release
branch into master, that should never have unintended consequences. This
strategy implies a little work when creating a release branch but that
should not happen that often. 

As of now, the third option is my favorite. We are supposed to compile a
fresh checkout of the release branch at least once before releasing it.
This build would fail if we forgot to clean up .gitignore and generate
the build system. 

But I may still change my mind and I am looking forward to reading about
your opinion! 

Le 10.02.2016 14:27, Othmar Truniger a écrit : 

> @2franix [1] This is normal for repositories from github because "git clone" does not keep file timestamps. Unfortunately this breaks build logic for make (if autotools are installed). There have been lots of discussions about this. We could add the macro AM_MAINTAINER_MODE in configure.ac (no problem with me) but then we always have to make sure that all files have to be regenerated for commit. Read about this on https://www.gnu.org/software/automake/manual/html_node/maintainer_002dmode.html 
> 
> --
> Reply to this email directly or view it on GitHub [2].

  

Links:
------
[1] https://github.com/2franix
[2] https://github.com/linknx/linknx/issues/15#issuecomment-182372107

**Comment by tru7** [comment]
@2franix I'm not very sure about this myself. I'm also with your option 3 or maybe option 4 - leave it the way it is now. I agree that branches or releases targeted for users must be complete and correctly generated. That means no problems for those without autotools and maybe an extra autoconf step for those with autotools.
With option 3 you make sure for master that the build system is generated before you compile the code but users testing master are stuck without autotools - which is solved by option 4. Option 4 also easies the part of creating branches or tags targeted for users.
My opinion: users with installed autotools must be able to deal with them. For the other users we have to make sure the build system is always up-to-date when committing. I think there are not that many occasions for changes in the build system, we can handle that.
Maybe we have to learn by time and maybe there are some best practices already around. I guess it's better not to deal with AM_MAINTAINER_MODE for now.

**Comment by 2franix** [comment]
> but users testing master are stuck without autotools
This is not a concern, to me. I do not see any reason for an end user (a non developer one, at least) to build the master branch. Despite our efforts, we cannot guarantee it is stable enough and we should always keep them away from this branch. This is why the README file will present quick links to download tagged releases.

Option 4 has a drawback: I am afraid the generated files would change unduly too often. We would either have useless revisions of these files in history or we would have to take care of not staging them for commit (meaning they would pollute the sandbox).

I am still voting for option 3. But I am fine with postponing the decision. As you suggested, time would show if the aforementioned disadvantage of option 4 is going to happen or not.

Anyway, there is still something I do not understand: the new generated files look really different from the original ones. I mean, if this is only due to broken timestamps, the regenerated files should be equal to the old ones, what do you think?

**Comment by tru7** [comment]
@2franix Ooops, that simply means that different versions of autotools on different OS environments and maybe with different other development tools generate different output files, which makes kind of sense. But somehow they still must be more or less equivalent logically. Mine look the same as on repository every time of course.
So option 3 is the one making most sense to me.
You should create a tag for the current status and release version linknx-0.0.1.33 before you start deleting files. And please omit the v in the release number as this may break some tool logic.

**Comment by 2franix** [comment]
Closed with a35b881.
