### ISSUE TITLE
Remove the obsolete linknx.spec file

### ISSUE THREAD

**Issue by 2franix** [linknx/linknx#16]
This file looks like the config for a rpm file. But it has not been maintained since 2011 and looks mostly outdated.
I would vote for its deletion unless someone argues against that.

**Comment by fraxinas** [comment]
i argue against that...
unfortunately all my work on getting linknx working nicely with system / rpm on https://github.com/fraxinas/linknx has been ignored :( 
i need to try to get everything back in sync with your current work
