### ISSUE TITLE
Compiler warnings on unclean source code

### ISSUE THREAD

**Issue by tru7** [linknx/linknx#17]
These three compiler warnings are issued:

ObjectTest.cpp: In member function ‘void ObjectTest::testS32Object()’:
ObjectTest.cpp:2657:36: warning: overflow in implicit constant conversion [-Woverflow]
         t.setIntValue(-2000000000UL);

XmlServerTest.cpp: In member function ‘virtual void XmlServerTest::setUp()’:
XmlServerTest.cpp:29:51: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
         system ("rm -rf /tmp/linknx_unittest_tmp");

XmlServerTest.cpp: In member function ‘int XmlServerTest::createMsgFd(const char*)’:
XmlServerTest.cpp:41:36: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
         write(fd, msg, strlen(msg));

**Comment by 2franix** [comment]
I fully agree these have to be fixed.
