### ISSUE TITLE
Move the wiki from sourceforge to github

### ISSUE THREAD

**Issue by 2franix** [linknx/linknx#18]
It would be cleaner to have everything hosted on github.
Take the opportunity of the move to fix a few formatting issues (I remember most XML samples are not well displayed).

**Comment by damago1** [comment]
I can help with that. I was the creator of a significant part of original documentation on SourceForge. But I do not have rights to edit wiki here.

**Comment by 2franix** [comment]
I'm closing this issue. I created [a more up-to-date copy of it](https://github.com/linknx/linknx-wiki/issues/2) in the project hosting the source files of the wiki.
