### ISSUE TITLE
Create Tag / Release for the project

### ISSUE THREAD

**Issue by condo4** [linknx/linknx#20]
Hi,

I work on a Yocto (OpenEmbedded) layer to build all KNX tool.
I want to integrate linknx in the project, and I choose to used your version.

With Yocto, this is better if a recipe use a Tag for 2 reasons:
- A tag don't move, since I need to add checksum in the recipe, this is better
- Github provide a way to download a release by downloading directly a tar.gz.

So, should you create a tag for the current last version 0.0.1.33, or a new release based on current master if you think last change stable ?

Thanks,
Fabien Proriol

**Comment by 2franix** [comment]
Yes, that requires a little bit of cleanup. Will do.

**Comment by 2franix** [comment]
Regarding the download of a specific version, Github works with branches as well. For 0.0.1.33, this is [here](https://github.com/linknx/linknx/archive/v0.0.1.33.zip). No need for a tag, here.
But you are true, there should be tags for releases, not branches, as releases represent static snapshots of the source code.

**Comment by 2franix** [comment]
Done with eb160953.
Let me know if that does not suffice.
