### ISSUE TITLE
Unable to start linknx with --daemon from systemd

### ISSUE THREAD

**Issue by itarch** [linknx/linknx#24]
Hi 

**I add linknx v0.0.1.33 in my setup (Rasp 3, Debian Jessie, knxd 0.11.9) and use systemd to control linknx start/stop/status. To do so, I add the following service file and performed necessary command (systemctl enable linknx). Everything is fine, except the fact that there is no logfile /var/log/linknx.log.** 
# > more /lib/systemd/system/linknx.service

[Unit]
Description=Linknx Daemon
After=network.target
[Service]
ExecStart=/usr/local/bin/linknx --config=/var/lib/linknx/linknx.xml --pid-file=/var/run/linknx.pid
Restart=on-failure
RestartSec=3
[Install]
WantedBy=multi-user.target

**When I add "--daemon=/var/log/linknx.log" in the [Service] section linknx does not start.**

**When I start linknx manually like this**
# > /usr/local/bin/linknx --config=/var/lib/linknx/linknx.xml --pid-file=/var/run/linknx.pid --daemon=/var/log/linknx.log

**everything is fine again.** 

**So why does linknx controlled by systemd not accept "--daemon=/var/log/linknx.log". What I see in /var/log/linknx.log is**
# > cat /var/log/linknx.xml

...
2016-10-21 12:00:29 [ INFO] main: Config file loaded: /var/lib/linknx/linknx.xml
2016-10-21 12:00:29 [ INFO] KnxConnection: KnxConnection: Group socket opened. Waiting for messages.
2016-10-21 12:00:30 [ INFO] Services: Stopping services
2016-10-21 12:00:30 [ INFO] KnxConnection: Out of KnxConnection loop.
...
**and systemd tells me that Linknx is started** 
# > systemctl status linknx

● linknx.service - Linknx Daemon
   Loaded: loaded (/lib/systemd/system/linknx.service; enabled)
   Active: inactive (dead) since Fri 2016-10-21 12:00:30 CEST; 2min 42s ago
  Process: 9276 ExecStart=/usr/local/bin/linknx --config=/var/lib/linknx/linknx.xml --pid-file=/var/run/linknx.pid --daemon=/var/log/linknx.log (code=exited, status=0/SUCCESS)
 Main PID: 9276 (code=exited, status=0/SUCCESS)
Oct 21 12:00:29 raspberrypi systemd[1]: Started Linknx Daemon.

**Kind Regards**

**Comment by 2franix** [comment]
Have you checked that there is no permission issue with /var/log/linknx.log?
I use quite the same config as yours, with systemd:
```
[Unit]
Description=Linknx Server
Requires=eibd.service
After=eibd.service

[Service]
ExecStart=/usr/local/bin/linknx --daemon=/var/log/linknx.log --config=/etc/linknx/linknx.conf.xml --pid-file=/var/run/knx/linknx.pid                                                                                                 
PIDFile=/var/run/knx/linknx.pid
Type=forking
Restart=always
User=linknx

[Install]
WantedBy=multi-user.target
```
and it works well.

How do you start eibd or knxd? I would expect to have a dependency between eibd/knxd and linknx in the systemd config.

**Comment by jef2000** [comment]
If you are using --daemon option, it means that linknx will fork itself to start in background. In this case, you need "Type=forking" in the "Service" section of your systemd config.

**Comment by tru7** [comment]
@jef2000 thank you for the hint. Handling linknx with systemd on Ubuntu 16.04 finally works for me.
