### ISSUE TITLE
uncommon directory structure

### ISSUE THREAD

**Issue by tru7** [linknx/linknx#4]
please omit the main directory linknx and move everything within one level up to support common compiling procedures.

**Comment by 2franix** [comment]
Can you please give a few details about those "common compiling procedures" you are referring to? Explain why the current file layout is not compliant with them.
That would help understand the reason for the move. Thanks!

**Comment by tru7** [comment]
@2franix your current github repository cannot be used with OpenWrt build environment because the macros expect all build files in the top directory of the master branch. That's why my pull request just moves everything one level up and deletes the unneeded linknx sub directory.

**Comment by 2franix** [comment]
Fixed with #6.
