### ISSUE TITLE
Move to Github Actions

### ISSUE THREAD

**Issue by 2franix** [linknx/linknx#52]
Replace the Travis integration with Github Actions.
- use a build matrix similar to the one in Travis
- make sure PRs require a build to pass
- replace the build badge in the README.md file

**Comment by damago1** [comment]
I am ready to contribute to the project. Especially on documentation side which needs a lot of cleanup, and also on the code itself. I was contributing to original SourceForge project. I did a significant part of original documentation there. 

I will be upgrading knx installation soon, which will include full reinstallation of linknx server. I am pretty sure I will find something. 

Also I would like to discuss one change proposal regarding actors which have two different GAD-s (group addresses) one to write (set) and one to read status. Currently it requires creating separate listener object which is error prone and complicates formulas in rules a lot. I will extend my proposal on this later. 

My account on github is damago1

How can I become contributor here and how can I get access to wiki to update it? I would like to start with wiki / documentation.

**Comment by 2franix** [comment]
This issue is now closed. A CI build automatically builds new changes pushed on master.

@damago1 As proposed in my email last week, the best way to contribute is through PRs. An preliminary issue is required to discuss any feature change before it is actually implemented. As for the wiki, I created [this repo](https://github.com/linknx/linknx-wiki) to mirror the content of the actual wiki – hosted on a repo that is not publicly visible. Same approach: submit an issue for anything you would like to work on. Once we made sure it does not conflict with other ongoing initiative, you can proceed with a pull request. Thanks!
