### ISSUE TITLE
configure: error: cannot run /bin/bash ./config.sub

### ISSUE THREAD

**Issue by gun777** [linknx/linknx#59]
Hi
The following happened to me during configure:
`configure: error: cannot run /bin/bash ./config.sub`
what can I do?
`https://github.com/linknx/linknx/archive/0.0.1.38.zip`
`Debian Buster 10 (stable)`

**Comment by 2franix** [comment]
Does the file exist? Does it have execution rights?
I suspect there was an earlier error that caused it not to be setup properly. Can you share the entire configure output?

**Comment by gun777** [comment]
`wget https://github.com/linknx/linknx/archive/0.0.1.38.zip
unzip 0.0.1.38.zip
cd linknx-0.0.1.38`

The entire configure output:
`./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ranlib... ranlib
configure: error: cannot run /bin/bash ./config.sub`

**Comment by gun777** [comment]
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by linknx configure 0.0.1.38, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##
## Platform. ##
## --------- ##

hostname = apu2deb
uname -m = x86_64
uname -r = 4.19.0-13-amd64
uname -s = Linux
uname -v = #1 SMP Debian 4.19.160-2 (2020-11-28)

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/local/games
PATH: /usr/games


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2577: checking for a BSD-compatible install
configure:2645: result: /usr/bin/install -c
configure:2656: checking whether build environment is sane
configure:2711: result: yes
configure:2860: checking for a thread-safe mkdir -p
configure:2899: result: /usr/bin/mkdir -p
configure:2906: checking for gawk
configure:2922: found /usr/bin/gawk
configure:2933: result: gawk
configure:2944: checking whether make sets $(MAKE)
configure:2966: result: yes
configure:2995: checking whether make supports nested variables
configure:3012: result: yes
configure:3203: checking for g++
configure:3219: found /usr/bin/g++
configure:3230: result: g++
configure:3257: checking for C++ compiler version
configure:3266: g++ --version >&5
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3277: $? = 0
configure:3266: g++ -v >&5
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 
configure:3277: $? = 0
configure:3266: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:3277: $? = 1
configure:3266: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'; did you mean '--version'?
g++: fatal error: no input files
compilation terminated.
configure:3277: $? = 1
configure:3297: checking whether the C++ compiler works
configure:3319: g++    conftest.cpp  >&5
configure:3323: $? = 0
configure:3371: result: yes
configure:3374: checking for C++ compiler default output file name
configure:3376: result: a.out
configure:3382: checking for suffix of executables
configure:3389: g++ -o conftest    conftest.cpp  >&5
configure:3393: $? = 0
configure:3415: result: 
configure:3437: checking whether we are cross compiling
configure:3445: g++ -o conftest    conftest.cpp  >&5
configure:3449: $? = 0
configure:3456: ./conftest
configure:3460: $? = 0
configure:3448: result: no
configure:3453: checking for suffix of object files
configure:3475: g++ -c   conftest.cpp >&5
configure:3479: $? = 0
configure:3500: result: o
configure:3504: checking whether we are using the GNU C++ compiler
configure:3523: g++ -c   conftest.cpp >&5
configure:3523: $? = 0
configure:3532: result: yes
configure:3541: checking whether g++ accepts -g
configure:3561: g++ -c -g  conftest.cpp >&5
configure:3561: $? = 0
configure:3602: result: yes
configure:3628: checking whether make supports the include directive
configure:3643: make -f confmf.GNU && cat confinc.out
this is the am__doit target
configure:3646: $? = 0
configure:3665: result: yes (GNU style)
configure:3690: checking dependency style of g++
configure:3801: result: gcc3
configure:3864: checking for gcc
configure:3880: found /usr/bin/gcc
configure:3891: result: gcc
configure:4120: checking for C compiler version
configure:4129: gcc --version >&5
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:4140: $? = 0
configure:4129: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 
configure:4140: $? = 0
configure:4129: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4140: $? = 1
configure:4129: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
configure:4140: $? = 1
configure:4144: checking whether we are using the GNU C compiler
configure:4163: gcc -c   conftest.c >&5
configure:4163: $? = 0
configure:4172: result: yes
configure:4181: checking whether gcc accepts -g
configure:4201: gcc -c -g  conftest.c >&5
configure:4201: $? = 0
configure:4242: result: yes
configure:4259: checking for gcc option to accept ISO C89
configure:4322: gcc  -c -g -O2  conftest.c >&5
configure:4322: $? = 0
configure:4335: result: none needed
configure:4360: checking whether gcc understands -c and -o together
configure:4382: gcc -c conftest.c -o conftest2.o
configure:4385: $? = 0
configure:4382: gcc -c conftest.c -o conftest2.o
configure:4385: $? = 0
configure:4397: result: yes
configure:4416: checking dependency style of gcc
configure:4527: result: gcc3
configure:4585: checking for ranlib
configure:4601: found /usr/bin/ranlib
configure:4612: result: ranlib
configure:4636: error: cannot run /bin/bash ./config.sub

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_c_compiler_gnu=yes
ac_cv_cxx_compiler_gnu=yes
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPPUNIT_CFLAGS_set=
ac_cv_env_CPPUNIT_CFLAGS_value=
ac_cv_env_CPPUNIT_LIBS_set=
ac_cv_env_CPPUNIT_LIBS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LOG4CPP_CFLAGS_set=
ac_cv_env_LOG4CPP_CFLAGS_value=
ac_cv_env_LOG4CPP_LIBS_set=
ac_cv_env_LOG4CPP_LIBS_value=
ac_cv_env_LUA_CFLAGS_set=
ac_cv_env_LUA_CFLAGS_value=
ac_cv_env_LUA_LIBS_set=
ac_cv_env_LUA_LIBS_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=
ac_cv_env_PKG_CONFIG_PATH_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_objext=o
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_ac_ct_CXX=g++
ac_cv_prog_ac_ct_RANLIB=ranlib
ac_cv_prog_cc_c89=
ac_cv_prog_cc_g=yes
ac_cv_prog_cxx_g=yes
ac_cv_prog_make_make_set=yes
am_cv_CC_dependencies_compiler_type=gcc3
am_cv_CXX_dependencies_compiler_type=gcc3
am_cv_make_support_nested_variables=yes
am_cv_prog_cc_c_o=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /home/gun/linknx-0.0.1.38/missing aclocal-1.16'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AUTOCONF='${SHELL} /home/gun/linknx-0.0.1.38/missing autoconf'
AUTOHEADER='${SHELL} /home/gun/linknx-0.0.1.38/missing autoheader'
AUTOMAKE='${SHELL} /home/gun/linknx-0.0.1.38/missing automake-1.16'
AWK='gawk'
CC='gcc'
CCDEPMODE='depmode=gcc3'
CFLAGS='-g -O2'
CPP=''
CPPFLAGS=''
CPPUNIT_CFLAGS=''
CPPUNIT_FALSE=''
CPPUNIT_LIBS=''
CPPUNIT_TRUE=''
CXX='g++'
CXXDEPMODE='depmode=gcc3'
CXXFLAGS='-g -O2'
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LDFLAGS=''
LIBCURL=''
LIBCURL_CPPFLAGS=''
LIBICONV=''
LIBOBJS=''
LIBS=''
LOG4CPP_CFLAGS=''
LOG4CPP_CONFIG=''
LOG4CPP_LIBS=''
LTLIBICONV=''
LTLIBOBJS=''
LUA_CFLAGS=''
LUA_LIBS=''
MAKEINFO='${SHELL} /home/gun/linknx-0.0.1.38/missing makeinfo'
MKDIR_P='/usr/bin/mkdir -p'
MYSQL_CFLAGS=''
MYSQL_CONFIG=''
MYSQL_LIBS=''
OBJEXT='o'
PACKAGE='linknx'
PACKAGE_BUGREPORT='cyrille.github@youplaboum.fr'
PACKAGE_NAME='linknx'
PACKAGE_STRING='linknx 0.0.1.38'
PACKAGE_TARNAME='linknx'
PACKAGE_URL=''
PACKAGE_VERSION='0.0.1.38'
PATH_SEPARATOR=':'
PKG_CONFIG='/usr/bin/pkg-config'
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
PTH_CFLAGS=''
PTH_CPPFLAGS=''
PTH_LDFLAGS=''
PTH_LIBS=''
RANLIB='ranlib'
SET_MAKE=''
SHELL='/bin/bash'
STRIP=''
USE_B64_FALSE=''
USE_B64_TRUE=''
VERSION='0.0.1.38'
_libcurl_config=''
ac_ct_CC='gcc'
ac_ct_CXX='g++'
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE='#'
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE='#'
am__fastdepCXX_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host=''
host_alias=''
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/gun/linknx-0.0.1.38/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "linknx"
#define PACKAGE_TARNAME "linknx"
#define PACKAGE_VERSION "0.0.1.38"
#define PACKAGE_STRING "linknx 0.0.1.38"
#define PACKAGE_BUGREPORT "cyrille.github@youplaboum.fr"
#define PACKAGE_URL ""
#define PACKAGE "linknx"
#define VERSION "0.0.1.38"

configure: exit 127

**Comment by 2franix** [comment]
The archive is indeed incomplete. As a temporary workaround, run ./bootstrap.sh then configure again. And in the meantime, I'll fix the release archive to make this step unnecessary.

**Comment by 2franix** [comment]
The archive for 0.0.1.38 has now been fixed. Running `bootstrap.sh` should not be necessary anymore.
Thanks for reporting this stupid mistake @gun777 !

**Comment by gun777** [comment]
@2franix thank you
