### ISSUE TITLE
rules created with flag active="no" have stateless actionlists executed on initialization

### ISSUE THREAD

**Issue by knxste** [linknx/linknx#71]
if I create a rule with active="no" and the rule has an "if-false" actionlist, this is executed on initialization, despite the rule is being created as inactive. It seems that method

void Rule::initialize()

in ruleserver.cpp is missing a statement like

if(flags_m & Active)

before executing stateless actionlists

**Comment by 2franix** [comment]
After reviewing the code, I agree there is something wrong with how initialization is managed with respect to the active status.
I am not sure @knxste's suggestion for a fix is the best approach, though. For instance, there does not seem to be any initialization done when an inactive rule is set to active. My rough guess without much thinking is to trigger initialization from within `Rule::setActive` and just skip the call of `Rule::initialize()` when creating an inactive rule. Its status would be left to `false`, no matter what its `init` attribute is set to.

My last concern is the fix will likely be a breaking change. I agree the current behavior looks like a bug but existing configurations may no longer work once we fix it. This change has to be properly documented in the release notes.

I have limited access to internet right now, but I am happy to give this issue more thoughts and maybe work on a fix sometime in the next two weeks, unless you submit one by then!

**Comment by knxste** [comment]
Thank you Cyrille for your prompt feedback. I agree with you that any fix would be a breaking change. Perhaps the best solution would be to keep track of this behaviour in the documentation. At the moment, the wiki reports that if the "init=" parameter is specified actionlists are not executed on initialization, which is true for "on-true" and "on-false" actionlists while stateless actionlists "if-true" or "if-false" are executed depending on the value of the "init=" parameter (see here https://github.com/linknx/linknx/wiki/Rules#initialization-upon-linknx-startup). Also mentioning the behaviour when "active=false" is specified would be IMHO useful. Many thanks again.

**Comment by knxste** [comment]
I checked the fix and it works as expected, many thanks again

**Comment by 2franix** [comment]
> I checked the fix and it works as expected, many thanks again

Thanks for letting me know. I merged #73, so make sure to install from the master branch from now on until there is a new release.
